[platformio]
default_envs = esp12f

[env:esp12f]
platform = espressif8266
board = esp12e
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../..
lib_ldf_mode = chain+
board_build.ldscript = ../../partitions/esp8266-4mb-2mfs.ld
build_flags =
    -DESP8266BASE_LOG_LEVEL=1
    -DESP8266BASE_USE_RECORD_STORE=1
    -DESP8266BASE_USE_WEB=1
    -DESP8266BASE_USE_OTA=1
    -DESP8266BASE_USE_SLEEP=1
    -DESP8266BASE_USE_FILELOG=0
    -DESP8266BASE_USE_MDNS=0
